"""add lap and trackpoint storage

Revision ID: 04da591b32f7
Revises: af10bb68d8e3
Created: 2026-08-26 16:53:36.326884
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "04da591b32f7"
down_revision: str | Sequence[str] | None = "af10bb68d8e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("lap_index", sa.Integer(), nullable=False),
        sa.Column("start_time_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("distance_m", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("moving_time_ms", sa.BigInteger(), nullable=True),
        sa.Column("elapsed_time_ms", sa.BigInteger(), nullable=True),
        sa.Column("elevation_gain_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("average_hr_bpm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("max_hr_bpm", sa.SmallInteger(), nullable=True),
        sa.Column("average_cadence_spm", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.CheckConstraint("distance_m IS NULL OR distance_m >= 0", name="laps_distance"),
        sa.CheckConstraint(
            "elapsed_time_ms IS NULL OR elapsed_time_ms >= 0", name="laps_elapsed_time"
        ),
        sa.CheckConstraint("lap_index >= 0", name="laps_index"),
        sa.CheckConstraint(
            "moving_time_ms IS NULL OR moving_time_ms >= 0", name="laps_moving_time"
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_laps_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_laps")),
        sa.UniqueConstraint("activity_id", "lap_index", name="uq_laps_activity_index"),
    )
    op.create_index("ix_laps_activity", "laps", ["activity_id"], unique=False)
    op.create_table(
        "trackpoints",
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("elapsed_ms", sa.BigInteger(), nullable=False),
        sa.Column("distance_m", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("altitude_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("heart_rate_bpm", sa.SmallInteger(), nullable=True),
        sa.Column("cadence_spm", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("speed_mps", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("power_watts", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("temperature_c", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("is_paused", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint("elapsed_ms >= 0", name="trackpoints_elapsed"),
        sa.CheckConstraint("sequence_number >= 0", name="trackpoints_sequence_number"),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_trackpoints_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("activity_id", "sequence_number", name=op.f("pk_trackpoints")),
    )
    op.create_index(
        "ix_trackpoints_activity_recorded",
        "trackpoints",
        ["activity_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "source_activity_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_activity_id", sa.Uuid(), nullable=False),
        sa.Column("import_file_id", sa.Uuid(), nullable=False),
        sa.Column("file_role", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_role IN ('summary', 'sensor', 'route', 'attachment')",
            name="source_activity_files_role",
        ),
        sa.ForeignKeyConstraint(
            ["import_file_id"],
            ["import_files.id"],
            name=op.f("fk_source_activity_files_import_file_id_import_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_activity_id"],
            ["source_activities.id"],
            name=op.f("fk_source_activity_files_source_activity_id_source_activities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_activity_files")),
        sa.UniqueConstraint(
            "source_activity_id", "import_file_id", name="uq_source_activity_files_source_file"
        ),
    )
    op.create_index(
        "ix_source_activity_files_import_file",
        "source_activity_files",
        ["import_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_source_activity_files_import_file", table_name="source_activity_files")
    op.drop_table("source_activity_files")
    op.drop_index("ix_trackpoints_activity_recorded", table_name="trackpoints")
    op.drop_table("trackpoints")
    op.drop_index("ix_laps_activity", table_name="laps")
    op.drop_table("laps")
    # ### end Alembic commands ###
