"""create documented ingestion schema

Revision ID: af10bb68d8e3
Revises:
Created: 2026-08-26 15:23:38.164700
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "af10bb68d8e3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_athletes")),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("sport", sa.String(length=32), nullable=False),
        sa.Column(
            "activity_type",
            sa.String(length=32),
            server_default=sa.text("'unknown'"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("start_time_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_timezone", sa.String(length=64), nullable=True),
        sa.Column("local_start_date", sa.Date(), nullable=False),
        sa.Column("distance_m", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("moving_time_ms", sa.BigInteger(), nullable=False),
        sa.Column("elapsed_time_ms", sa.BigInteger(), nullable=False),
        sa.Column("elevation_gain_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("average_hr_bpm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("max_hr_bpm", sa.SmallInteger(), nullable=True),
        sa.Column("average_cadence_spm", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("calories_kcal", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("canonical_sensor_source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "verification_status",
            sa.String(length=16),
            server_default=sa.text("'unverified'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_type IN ('race', 'workout', 'easy', 'long', 'unknown', 'other')",
            name="activities_type",
        ),
        sa.CheckConstraint(
            "verification_status IN ('unverified', 'verified', 'excluded')",
            name="activities_verification_status",
        ),
        sa.CheckConstraint("distance_m >= 0", name="activities_distance"),
        sa.CheckConstraint("elapsed_time_ms >= 0", name="activities_elapsed_time"),
        sa.CheckConstraint("moving_time_ms >= 0", name="activities_moving_time"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
            name=op.f("fk_activities_athlete_id_athletes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(
        "ix_activities_duplicate_candidates",
        "activities",
        ["athlete_id", "sport", "start_time_utc"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("parser_bundle_version", sa.String(length=64), nullable=False),
        sa.Column("total_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("accepted_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rejected_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duplicate_files", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("warning_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sanitized_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'completed_with_warnings', 'failed')",
            name="import_batches_status",
        ),
        sa.CheckConstraint("accepted_files >= 0", name="import_batches_accepted_files"),
        sa.CheckConstraint("duplicate_files >= 0", name="import_batches_duplicate_files"),
        sa.CheckConstraint("rejected_files >= 0", name="import_batches_rejected_files"),
        sa.CheckConstraint("retry_count >= 0", name="import_batches_retry_count"),
        sa.CheckConstraint("total_files >= 0", name="import_batches_total_files"),
        sa.CheckConstraint("warning_count >= 0", name="import_batches_warning_count"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
            name=op.f("fk_import_batches_athlete_id_athletes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        "ix_import_batches_athlete_requested",
        "import_batches",
        ["athlete_id", "requested_at"],
        unique=False,
    )
    op.create_table(
        "import_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column("source_provider", sa.String(length=16), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("detected_format", sa.String(length=32), nullable=True),
        sa.Column("parser_name", sa.String(length=128), nullable=True),
        sa.Column("parser_version", sa.String(length=64), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source_provider IN ('garmin', 'strava', 'unknown')",
            name="import_files_source_provider",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected', 'duplicate', 'failed', 'deleted')",
            name="import_files_status",
        ),
        sa.CheckConstraint("size_bytes >= 0", name="import_files_size"),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_files_import_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_files")),
    )
    op.create_index("ix_import_files_batch", "import_files", ["import_batch_id"], unique=False)
    op.create_index("ix_import_files_sha256", "import_files", ["sha256"], unique=False)
    op.create_table(
        "source_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_file_id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("external_activity_id", sa.String(length=128), nullable=True),
        sa.Column("source_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_sport", sa.String(length=64), nullable=True),
        sa.Column("source_distance_m", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("source_duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("dedupe_fingerprint", sa.CHAR(length=64), nullable=True),
        sa.Column(
            "resolution_status",
            sa.String(length=16),
            server_default=sa.text("'unresolved'"),
            nullable=False,
        ),
        sa.Column(
            "raw_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('garmin', 'strava', 'unknown')", name="source_activities_provider"
        ),
        sa.CheckConstraint(
            "resolution_status IN ('unresolved', 'canonical', 'duplicate', 'review')",
            name="source_activities_resolution_status",
        ),
        sa.CheckConstraint(
            "source_distance_m IS NULL OR source_distance_m >= 0", name="source_activities_distance"
        ),
        sa.CheckConstraint(
            "source_duration_ms IS NULL OR source_duration_ms >= 0",
            name="source_activities_duration",
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_source_activities_activity_id_activities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["import_file_id"],
            ["import_files.id"],
            name=op.f("fk_source_activities_import_file_id_import_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_activities")),
        sa.UniqueConstraint(
            "provider", "external_activity_id", name="uq_source_activities_provider_external"
        ),
    )
    op.create_index(
        "ix_source_activities_activity", "source_activities", ["activity_id"], unique=False
    )
    op.create_index(
        "ix_source_activities_dedupe", "source_activities", ["dedupe_fingerprint"], unique=False
    )
    op.create_index(
        "ix_source_activities_import_file", "source_activities", ["import_file_id"], unique=False
    )
    op.create_foreign_key(
        "fk_activities_canonical_sensor_source_id_source_activities",
        "activities",
        "source_activities",
        ["canonical_sensor_source_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "activity_field_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("source_activity_id", sa.Uuid(), nullable=False),
        sa.Column("selection_reason", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_field_sources_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_activity_id"],
            ["source_activities.id"],
            name=op.f("fk_activity_field_sources_source_activity_id_source_activities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_field_sources")),
        sa.UniqueConstraint(
            "activity_id", "field_name", name="uq_activity_field_sources_activity_field"
        ),
    )
    op.create_index(
        "ix_activity_field_sources_source",
        "activity_field_sources",
        ["source_activity_id"],
        unique=False,
    )
    op.create_table(
        "data_quality_issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("source_activity_id", sa.Uuid(), nullable=True),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "observed_value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "resolution_status",
            sa.String(length=16),
            server_default=sa.text("'open'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "resolution_status IN ('open', 'accepted', 'corrected', 'dismissed')",
            name="data_quality_issues_resolution_status",
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error', 'blocking')",
            name="data_quality_issues_severity",
        ),
        sa.CheckConstraint(
            "import_batch_id IS NOT NULL "
            "OR source_activity_id IS NOT NULL "
            "OR activity_id IS NOT NULL",
            name="data_quality_issues_scope",
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_data_quality_issues_activity_id_activities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_data_quality_issues_import_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_activity_id"],
            ["source_activities.id"],
            name=op.f("fk_data_quality_issues_source_activity_id_source_activities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_issues")),
    )
    op.create_index(
        "ix_data_quality_issues_activity", "data_quality_issues", ["activity_id"], unique=False
    )
    op.create_index(
        "ix_data_quality_issues_batch", "data_quality_issues", ["import_batch_id"], unique=False
    )
    op.create_index(
        "ix_data_quality_issues_source", "data_quality_issues", ["source_activity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_data_quality_issues_source", table_name="data_quality_issues")
    op.drop_index("ix_data_quality_issues_batch", table_name="data_quality_issues")
    op.drop_index("ix_data_quality_issues_activity", table_name="data_quality_issues")
    op.drop_table("data_quality_issues")
    op.drop_index("ix_activity_field_sources_source", table_name="activity_field_sources")
    op.drop_table("activity_field_sources")
    op.drop_constraint(
        "fk_activities_canonical_sensor_source_id_source_activities",
        "activities",
        type_="foreignkey",
    )
    op.drop_index("ix_source_activities_import_file", table_name="source_activities")
    op.drop_index("ix_source_activities_dedupe", table_name="source_activities")
    op.drop_index("ix_source_activities_activity", table_name="source_activities")
    op.drop_table("source_activities")
    op.drop_index("ix_import_files_sha256", table_name="import_files")
    op.drop_index("ix_import_files_batch", table_name="import_files")
    op.drop_table("import_files")
    op.drop_index("ix_import_batches_athlete_requested", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index("ix_activities_duplicate_candidates", table_name="activities")
    op.drop_table("activities")
    op.drop_table("athletes")
    # ### end Alembic commands ###
