"""add deterministic analytics tables

Revision ID: b21e5b4d8e3e
Revises: 04da591b32f7
Created: 2026-08-27 15:26:30.671412
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b21e5b4d8e3e"
down_revision: str | Sequence[str] | None = "04da591b32f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_loads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("load_method", sa.String(length=64), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("daily_load", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("acute_load", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("chronic_load", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("fitness_index", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("fatigue_index", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("form_index", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("coverage_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("acute_load IS NULL OR acute_load >= 0", name="daily_loads_acute_load"),
        sa.CheckConstraint(
            "chronic_load IS NULL OR chronic_load >= 0", name="daily_loads_chronic_load"
        ),
        sa.CheckConstraint("coverage_pct BETWEEN 0 AND 100", name="daily_loads_coverage"),
        sa.CheckConstraint("daily_load >= 0", name="daily_loads_daily_load"),
        sa.CheckConstraint(
            "fatigue_index IS NULL OR fatigue_index >= 0", name="daily_loads_fatigue_index"
        ),
        sa.CheckConstraint(
            "fitness_index IS NULL OR fitness_index >= 0", name="daily_loads_fitness_index"
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
            name=op.f("fk_daily_loads_athlete_id_athletes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_loads")),
        sa.UniqueConstraint(
            "athlete_id",
            "local_date",
            "load_method",
            "algorithm_version",
            name="uq_daily_loads_athlete_date_method_version",
        ),
    )
    op.create_index(
        "ix_daily_loads_athlete_date", "daily_loads", ["athlete_id", "local_date"], unique=False
    )
    op.create_table(
        "physiology_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("observed_max_hr_bpm", sa.SmallInteger(), nullable=True),
        sa.Column("resting_hr_bpm", sa.SmallInteger(), nullable=True),
        sa.Column("lactate_threshold_hr_bpm", sa.SmallInteger(), nullable=True),
        sa.Column("threshold_pace_seconds_per_km", sa.Integer(), nullable=True),
        sa.Column("zone_method", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lactate_threshold_hr_bpm IS NULL OR lactate_threshold_hr_bpm BETWEEN 80 AND 230",
            name="physiology_profiles_threshold_hr",
        ),
        sa.CheckConstraint(
            "observed_max_hr_bpm IS NULL OR observed_max_hr_bpm BETWEEN 100 AND 250",
            name="physiology_profiles_max_hr",
        ),
        sa.CheckConstraint(
            "resting_hr_bpm IS NULL OR resting_hr_bpm BETWEEN 25 AND 120",
            name="physiology_profiles_resting_hr",
        ),
        sa.CheckConstraint(
            "threshold_pace_seconds_per_km IS NULL OR threshold_pace_seconds_per_km > 0",
            name="physiology_profiles_threshold_pace",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="physiology_profiles_valid_period"
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
            name=op.f("fk_physiology_profiles_athlete_id_athletes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_physiology_profiles")),
        sa.UniqueConstraint(
            "athlete_id", "valid_from", name="uq_physiology_profiles_athlete_valid_from"
        ),
    )
    op.create_index(
        "ix_physiology_profiles_athlete_period",
        "physiology_profiles",
        ["athlete_id", "valid_from", "valid_to"],
        unique=False,
    )
    op.create_table(
        "activity_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("input_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("average_pace_seconds_per_km", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("heart_rate_coverage_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("gps_coverage_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("cadence_coverage_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("load_method", sa.String(length=64), nullable=False),
        sa.Column("training_load", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "zone_distribution",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "additional_metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cadence_coverage_pct BETWEEN 0 AND 100", name="activity_metrics_cadence_coverage"
        ),
        sa.CheckConstraint(
            "gps_coverage_pct BETWEEN 0 AND 100", name="activity_metrics_gps_coverage"
        ),
        sa.CheckConstraint(
            "heart_rate_coverage_pct BETWEEN 0 AND 100", name="activity_metrics_hr_coverage"
        ),
        sa.CheckConstraint("length(input_hash) = 64", name="activity_metrics_input_hash"),
        sa.CheckConstraint(
            "training_load IS NULL OR training_load >= 0", name="activity_metrics_training_load"
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_metrics_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["physiology_profiles.id"],
            name=op.f("fk_activity_metrics_profile_id_physiology_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_metrics")),
        sa.UniqueConstraint(
            "activity_id",
            "algorithm_version",
            "input_hash",
            name="uq_activity_metrics_activity_version_input",
        ),
    )
    op.create_index(
        "ix_activity_metrics_activity_calculated",
        "activity_metrics",
        ["activity_id", "calculated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_metrics_activity_calculated", table_name="activity_metrics")
    op.drop_table("activity_metrics")
    op.drop_index("ix_physiology_profiles_athlete_period", table_name="physiology_profiles")
    op.drop_table("physiology_profiles")
    op.drop_index("ix_daily_loads_athlete_date", table_name="daily_loads")
    op.drop_table("daily_loads")
    # ### end Alembic commands ###
