"""create core ingestion schema

Revision ID: b454fec25760
Revises:
Created: 2026-08-26 15:01:27.697239
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b454fec25760"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_athletes")),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_key", sa.String(length=64), nullable=False),
        sa.Column("activity_kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("elapsed_time_s", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("moving_time_s", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("distance_m", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("elevation_gain_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("elevation_loss_m", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("average_speed_mps", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("maximum_speed_mps", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("average_heart_rate_bpm", sa.Integer(), nullable=True),
        sa.Column("maximum_heart_rate_bpm", sa.Integer(), nullable=True),
        sa.Column("average_cadence_spm", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("maximum_cadence_spm", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("calories_kcal", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("provider_vo2max", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "provider_aerobic_training_effect", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "provider_anaerobic_training_effect", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("provider_training_effect_label", sa.String(length=64), nullable=True),
        sa.Column("has_gps", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_kind IN ('running', 'trail_running', 'treadmill_running', 'other')",
            name="activities_kind",
        ),
        sa.CheckConstraint("distance_m IS NULL OR distance_m >= 0", name="activities_distance"),
        sa.CheckConstraint(
            "elapsed_time_s IS NULL OR elapsed_time_s >= 0", name="activities_elapsed_time"
        ),
        sa.CheckConstraint(
            "moving_time_s IS NULL OR moving_time_s >= 0", name="activities_moving_time"
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
            name=op.f("fk_activities_athlete_id_athletes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
        sa.UniqueConstraint(
            "athlete_id", "canonical_key", name="uq_activities_athlete_canonical_key"
        ),
    )
    op.create_index(
        "ix_activities_athlete_kind", "activities", ["athlete_id", "activity_kind"], unique=False
    )
    op.create_index(
        "ix_activities_athlete_started", "activities", ["athlete_id", "started_at"], unique=False
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("source_description", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')", name="import_batches_status"
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
            name=op.f("fk_import_batches_athlete_id_athletes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        "ix_import_batches_athlete_started",
        "import_batches",
        ["athlete_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "source_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "parse_status",
            sa.String(length=16),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parse_status IN ('pending', 'parsed', 'rejected', 'failed')",
            name="source_files_parse_status",
        ),
        sa.CheckConstraint("provider IN ('garmin', 'strava')", name="source_files_provider"),
        sa.CheckConstraint("size_bytes >= 0", name="source_files_size"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
            name=op.f("fk_source_files_athlete_id_athletes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_source_files_import_batch_id_import_batches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_files")),
        sa.UniqueConstraint(
            "athlete_id", "provider", "content_sha256", name="uq_source_files_athlete_provider_hash"
        ),
    )
    op.create_index(
        "ix_source_files_import_batch", "source_files", ["import_batch_id"], unique=False
    )
    op.create_table(
        "activity_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("source_format", sa.String(length=16), nullable=False),
        sa.Column("source_record_key", sa.String(length=128), nullable=False),
        sa.Column("external_activity_id", sa.String(length=128), nullable=True),
        sa.Column("source_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("matched_by", sa.String(length=64), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider IN ('garmin', 'strava')", name="activity_sources_provider"),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_sources_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_files.id"],
            name=op.f("fk_activity_sources_source_file_id_source_files"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_sources")),
        sa.UniqueConstraint(
            "source_file_id", "source_record_key", name="uq_activity_sources_file_record"
        ),
    )
    op.create_index(
        "ix_activity_sources_activity", "activity_sources", ["activity_id"], unique=False
    )
    op.create_index(
        "ix_activity_sources_provider_external",
        "activity_sources",
        ["provider", "external_activity_id"],
        unique=False,
    )
    op.create_table(
        "validation_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_file_id", sa.Uuid(), nullable=True),
        sa.Column("activity_id", sa.Uuid(), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error')", name="validation_findings_severity"
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_validation_findings_activity_id_activities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_validation_findings_import_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["source_files.id"],
            name=op.f("fk_validation_findings_source_file_id_source_files"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_findings")),
    )
    op.create_index(
        "ix_validation_findings_activity", "validation_findings", ["activity_id"], unique=False
    )
    op.create_index(
        "ix_validation_findings_batch", "validation_findings", ["import_batch_id"], unique=False
    )
    op.create_table(
        "activity_field_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("activity_source_id", sa.Uuid(), nullable=False),
        sa.Column("selection_reason", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_field_sources_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["activity_source_id"],
            ["activity_sources.id"],
            name=op.f("fk_activity_field_sources_activity_source_id_activity_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_field_sources")),
        sa.UniqueConstraint(
            "activity_id", "field_name", name="uq_activity_field_sources_activity_field"
        ),
    )
    op.create_index(
        "ix_activity_field_sources_source",
        "activity_field_sources",
        ["activity_source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_field_sources_source", table_name="activity_field_sources")
    op.drop_table("activity_field_sources")
    op.drop_index("ix_validation_findings_batch", table_name="validation_findings")
    op.drop_index("ix_validation_findings_activity", table_name="validation_findings")
    op.drop_table("validation_findings")
    op.drop_index("ix_activity_sources_provider_external", table_name="activity_sources")
    op.drop_index("ix_activity_sources_activity", table_name="activity_sources")
    op.drop_table("activity_sources")
    op.drop_index("ix_source_files_import_batch", table_name="source_files")
    op.drop_table("source_files")
    op.drop_index("ix_import_batches_athlete_started", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index("ix_activities_athlete_started", table_name="activities")
    op.drop_index("ix_activities_athlete_kind", table_name="activities")
    op.drop_table("activities")
    op.drop_table("athletes")
    # ### end Alembic commands ###
